### ISSUE TITLE
change website to be file based instead of all in Wordpress

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#182]

**Comment by obowersa** [comment]
Hey Folk,

A couple of updates on this, some questions we need to think about and general discussion.

I've put together a barebones demo repo here: https://github.com/obowersa/ort-netlify

A couple of notes on this:
- The repo is barebones, based around hugo/docsy ( which we already use for the documentation site ). As it stands it has a handful of headings and a working deployment mechanism.
- The site is currently deployed via netlify with preview deploys enabled. I also have a working deployment against AWS with preview URL's able to be generated/torn-down but it's a little rough.
- There are currently no layouts specified.

The above three points lead to the main questions, primarily, do we want to use hugo/docsy, how do we want to deploy the site and do we want to match the existing wp layout as closely as possible.

1: Hugo/Docsy
I'm a fan of the combination, and we're already using it for the documentation side which is a plus. There is a lot which can be done as far as layout customization goes ( a great example is the kubernetes contributor site: https://www.kubernetes.dev/ ). Flexibility wise it gives us a lot and has a lot of community support around it, but it's worth continuing the discussion we had previously.


2: Deploying
This I think is the big open question as it has potential cost implications. Essentially, what is the target deployment for the site. Currently I've used netlify for ease of demonstration of the preview functionality, but getting the same workflow working with AWS/Azure/GCP should be doable ( for AWS/Azure I've done similar before, would need to dig into the GCP side. )

One thing worth mentioning with Netlify is they do have a pretty decent open source plan, which would be of relevance: https://www.netlify.com/legal/open-source-policy/  

Or we could have this working as a deployment to a k8s cluster and containerize the site component. It would be great to clarify where we're currently deploying the docs site to and potentially matching that while adding preview functionality. 

3: Layouts
This is really a question of how closely do we want to match the current site layout and how we want to approach the work on this. I can get us going with a fairly basic layout which will be similar to what we've got now if that works as a starter for ten.


There is the larger question of content migration, but I think figuring out the above is a great starting point. Deployment in particular.


----

Outside of the questions, I've set this up in a separate repo for demo purposes so feel free to have a play around. Pull requests submitted against the repo will trigger a build/deploy on netlify and build messages attached to the PR. Clicking on the details link for the deployment will load the preview site.

Regardless of what deployment mechanism we go with, I'll look to implement some form of preview functionality as it's really powerful for giving confidence in documentation edits without needing to have the full tool suite running locally.

I've left an open PR against the repo so folk can take an easy look at that side of it: 

PR: https://github.com/obowersa/ort-netlify/pull/1

Base site: https://peaceful-bhaskara-fc75a4.netlify.app/

Preview Site: https://deploy-preview-1--peaceful-bhaskara-fc75a4.netlify.app/

**Comment by sbtaylor15** [comment]
@obowersa the docs.ortelius.io is a hugo server running as a container in our Azure k8s cluster.  Builds are setup to create the container on a PR.  Ortelius is hooked is to grab the necessary info for deployments.  The Linux Foundation will pick up the cost of running our cluster.  

I will look at the site on netify and play with it.  Thanks for working on this.

**Comment by obowersa** [comment]
No problem! I’m currently putting together a couple of initial themes and moving over a couple of bits of content to give more of a ‘feel’ for it.

On the azure front, AKS makes generate preview URLs fairly straight forward depending on the config. We can utilise the azure service annotation  to generate a public facing dev url, the annotation is along the lines off ‘ service.beta.kubernetes.io/azure-dns-label-name’

Which can generate a url of <label-name>.<location>.cloudapp.azure.com.

It’s then just a case of doing appropriate tear down/creation with the pipeline. 

I can pull together an example pipeline for the repo with this in place against my aks setup to work as a starting point if we want to go this route, essentially similar to what we’ve got for the docs but with the generates preview url for the pr. 


- Owen

**Comment by sbtaylor15** [comment]
@obowersa fyi, we have istio as part of the cluster and currently routing the docs.ortelius.io url to the docs container.  We could do a dev.ortelius.io for a branch update and www.ortelius.io for the prod (master branch).  Istio would route based on domain url to the correct backend.

**Comment by obowersa** [comment]
Ok, cool. I was hoping we could achieve a short lived url per pr, but I'll need to catch up with you on the aks/istio setup. I'll look to do that via discord.

At a high level ( and my istio knowledge is a little rusty! ), if the istio operator is in use I think it's a case of generating a new entry in the list with the correct label, a little like this:
```

---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - namespace: <defined_namespace>
        name: ortsite-pr-<generated_number> 
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 200m
          serviceAnnotations:
            service.beta.kubernetes.io/azure-dns-label-name: ortsite-pr-<number>
          service:
            ports:
            - port: <external_port>
              targetPort: 80 

---
```
Anyhow. Going to progress a couple of the layout bits and will update once that's there and will touch base on the aks side.

**Comment by sbtaylor15** [comment]
@obowersa  The gateway will be predefined to handle the ingress on a static ip.  From there a VirtualService and DestinationRoute would be used to get the traffic to the right backend container.  Annotations and labels are used to identify two different versions of the container image running. 

I think this is what istio defintion will look like (should be close)

```
---
#
# docs.ortelius.io - hugo/docsy guides container
#
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ortelius-docs
spec:
  hosts:
    - "docs.ortelius.io"
  gateways:
    - ortelius-gateway
  http:
  - match:
    - uri:
        regex: '.*'       
    route:
    - destination:
        host: ortelius-docs
        port: 
          number: 80  
---
#
# Websites
#
# Create a rule to route to the right container
#   ortelius-www prod routes to the ortelius-www container version-1
#   ortelius-www dev  routes to the ortelius-www container version-2
#
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ortelius-www
spec:
  host: ortelius-www
  subsets:
  - name: prod
    labels:
      version: version-1
  - name: dev
    labels:
      version: version-2  
---    
#
# Virtual Service to route traffic to www.ortelius.io to 
# the destination rule ortelius-www subset prod
#  
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ortelius-www
spec:
  hosts:
    - www.ortelius.io
  gateways:
    - ortelius-gateway
  http:   
    route:
    - destination:
        host: ortelius-www
        subset: prod
        port: 
          number: 80  
---    
#
# Virtual Service to route traffic to dev.ortelius.io to 
# the destination rule ortelius-www subset dev
#    
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ortelius-dev
spec:
  hosts:
    - dev.ortelius.io
  gateways:
    - ortelius-gateway
  http:   
    route:
    - destination:
        host: ortelius-www
        subset: dev
        port: 
          number: 80                       
```

The destination rule is what will be updated as part of the deployment in which we will update the new containers label, ie the PR.   I believe that we can make it work without the destination rule, just more flexibility if we use one.
