### ISSUE TITLE
Add super-linter to GH Actions on all microservice repos

### ISSUE THREAD

**Issue by sbtaylor15** [ortelius/ortelius#573]

**Comment by sbtaylor15** [comment]
## Step similar to this should to be added after the checkout

```yaml
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

[SuperLinter Docs](https://github.com/github/super-linter)

We should start with just linting the python code, GH Actions and the docker files.

VALIDATE_ALL_CODEBASE=false
VALIDATE_GITHUB_ACTIONS=true
VALIDATE_PYTHON=true
VALIDATE_DOCKERFILE_HADOLINT=true

**Comment by sbtaylor15** [comment]
I was able to figure out the super-linter for the [ms-dep-pkg-r repo](https://github.com/ortelius/ms-dep-pkg-r).  Below is the set up.  

> Note: Super-linter found errors that needed to be corrected in  order to get a clean code base.  So commits were done to correct/cleanup the codebase.

## Repo Setup

.github/workflows/build-push-chart.yml

```yaml
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_MARKDOWN: true
```

.github/linters/.flake8

```toml
[flake8]
ignore = E203, E266, E501, W503, F403, F401
max-line-length = 200
max-complexity = 30
select = B,C,E,F,W,T4,B9
```

.github/linters/.python-black

```toml
[tool.black]
line-length = 200
```

## pre-commit.com config

$HOME/.git-template/pre-commit-config.yaml 

> Note; Update args for black and flake8 to point to your Home Directory for the linter config files.  The linter config files are the same as in the .github/linters directory

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: .svg|.sarif
    -   id: end-of-file-fixer
        exclude: .svg|.sarif
    -   id: check-added-large-files
    -   id: check-json
        exclude: .svg|themes/docsy/
    -   id: check-toml
        exclude: .svg|.sarif
    -   id: check-xml
        exclude: .svg|themes/docsy/|.sarif
    -   id: check-yaml
        exclude: installers/helm|chart/|.svg|.sarif
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.11
      args: [--config, /Users/steve/.git-template/.python-black]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: [--config, /Users/steve/.git-template/.flake8]
```

Running pre-commit manually from the root of the repo

```bash
pre-commit run --all-files --config=$HOME/.git-template/pre-commit-config.yaml
```
